//
//  ConversionWorker.swift
//  Project1
//
//  Created by Mihai Cristescu on 17/12/2017.
//  Copyright (c) 2017 Mihai Cristescu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ConversionWorker {
    func convertToMilimeters(valueInM: Double) -> Double {
        return valueInM * 1000.0;
    }
    
    func convertToKilometers(valueInM: Double) -> Double {
        return valueInM / 1000.0;
    }
}
